-- FOH Maintenance — Alessandro through Tell us, 29 Sep 2026 (inbox c4ff2eae):
-- "a section dedicated to the maintenance work that needs to be done inside the restaurant ...
--  that everyone can be aware of what has been already reported and what is not".
-- Francesco, 7 Oct 2026: FOH gets its OWN list (not the Kitchen's); a FOH repair is signed off by
-- the FOH managers (Alessandro Longhi, Jins Thomas, Diego Tella); the technician will be Oliver,
-- starting in about a week — the section must be ready before he starts.
--
-- Same design as the Kitchen's Maintenance (maintenance-schema.sql in the Kitchen repo):
--   · anyone with a FOH employee ID reports a problem (where, what, what is wrong, photos/video)
--     and sees every card already reported — that list is the whole point of the request
--   · the technician opening a card is the moment it was READ (New -> Acknowledged); he moves it
--     In progress / On hold, writes his assessment, completes it signing with his employee ID
--   · a completed card stays open until a FOH manager checks the repair and signs (not the same
--     person who signed as technician), or sends it back
--   · roles are ROWS in fmaint_people, not code: adding Oliver = one insert, no deploy
--   · no technician yet -> a new card's email goes to the managers, so nothing is reported into
--     silence before Oliver starts
--
-- Every table is RLS-on with NO policy; everything goes through security-definer fmaint_* functions.
-- Emails are QUEUED by the database (fmaint_mail) and sent by the edge function foh-maint-notify,
-- which the database calls through pg_net. The app never calls it.
-- TEST: a reporter whose name starts "zz", or equipment starting "zz", makes a test card: its mail
-- goes to Francesco only with [TEST], and it is left out of the Home tile count.
--
-- FOH database: paoaivwtkzujmrgrfjuq

create table if not exists fmaint_people (
  staff_id uuid not null references foh_staff(id),
  role text not null check (role in ('technician','manager')),
  email text not null,
  active boolean not null default true,
  primary key (staff_id, role)
);

create table if not exists fmaint_cards (
  id uuid primary key default gen_random_uuid(),
  card_no bigint generated by default as identity unique,
  is_test boolean not null default false,
  reported_by_id uuid, reported_by text not null, reported_at timestamptz not null default now(),
  location text not null, equipment text not null, problem text not null,
  media jsonb not null default '[]'::jsonb,
  status text not null default 'new' check (status in ('new','acknowledged','in_progress','on_hold','completed')),
  read_at timestamptz, read_by text,
  tech_id uuid, tech_name text,
  started_at timestamptz, hold_at timestamptz, hold_reason text,
  diagnosis text, cause text, solution text, est_cost numeric(12,2), est_time text, parts text, notes text,
  assessed_at timestamptz, assessed_by text,
  work_done text, final_cost numeric(12,2), completed_at timestamptz,
  tech_signed_id uuid, tech_signed_by text,
  checked_at timestamptz, checked_id uuid, checked_by text,
  sent_back_at timestamptz, sent_back_by text, sent_back_note text,
  updated_at timestamptz not null default now()
);
create index if not exists fmaint_cards_open on fmaint_cards(checked_at, status);

create table if not exists fmaint_mail (
  id bigint generated by default as identity primary key,
  card_id uuid not null references fmaint_cards(id) on delete cascade,
  kind text not null check (kind in ('new','check')),
  to_list text[] not null,
  is_test boolean not null default false,
  status text not null default 'queued' check (status in ('queued','sending','sent','failed')),
  tries int not null default 0,
  resend_id text, error text,
  created_at timestamptz not null default now(), sent_at timestamptz
);
create index if not exists fmaint_mail_status on fmaint_mail(status, created_at);

alter table fmaint_people enable row level security;
alter table fmaint_cards  enable row level security;
alter table fmaint_mail   enable row level security;
revoke all on fmaint_people, fmaint_cards, fmaint_mail from anon, authenticated;

-- ── who is who ────────────────────────────────────────────────────────────
-- Sign-in is the employee ID in foh_staff (the same one Checklists and the Food Bible use).
create or replace function fmaint_who(p_emp text) returns foh_staff
language plpgsql stable security definer set search_path to 'public' as $$
declare s foh_staff;
begin
  if length(trim(coalesce(p_emp,''))) < 2 then raise exception 'no_emp' using errcode = 'P0001'; end if;
  -- 1212 and the personal master codes (foh-master-code.sql) open it too, as an admin who is NOT a
  -- foh_staff row (Francesco must never appear on a roster). Fixed id, never a real staff id.
  -- The admin has the MANAGER powers (sign off, send back) but not the technician's: opening a card
  -- as technician stamps it Acknowledged, and an admin looking must never read as "the technician saw it".
  if trim(p_emp) = '1212' or foh_master_name(p_emp) is not null then
    s.id := '00000000-0000-0000-0000-000000001212';
    s.name := coalesce(foh_master_name(p_emp), 'Admin');
    s.role := 'Admin';
    s.emp_id := trim(p_emp);
    s.active := true;
    return s;
  end if;
  select * into s from foh_staff where active and trim(emp_id) = trim(p_emp) order by created_at limit 1;
  if s.id is null then raise exception 'no_emp' using errcode = 'P0001'; end if;
  return s;
end $$;
revoke all on function fmaint_who(text) from public, anon, authenticated;

create or replace function fmaint_has(p_staff uuid, p_role text) returns boolean
language sql stable security definer set search_path to 'public' as $$
  select exists(select 1 from fmaint_people where staff_id = p_staff and role = p_role and active)
      or (p_role = 'manager' and p_staff = '00000000-0000-0000-0000-000000001212'::uuid)
$$;

create or replace function fmaint_me(p_emp text) returns jsonb
language plpgsql stable security definer set search_path to 'public' as $$
declare s foh_staff;
begin
  s := fmaint_who(p_emp);
  return jsonb_build_object('name', s.name, 'role', s.role,
    'tech', fmaint_has(s.id,'technician'), 'manager', fmaint_has(s.id,'manager'),
    'techs', (select coalesce(jsonb_agg(st.name order by st.name), '[]'::jsonb) from fmaint_people mp join foh_staff st on st.id = mp.staff_id where mp.role='technician' and mp.active and st.name !~* '^zz'),
    'managers', (select coalesce(jsonb_agg(st.name order by st.name), '[]'::jsonb) from fmaint_people mp join foh_staff st on st.id = mp.staff_id where mp.role='manager' and mp.active and st.name !~* '^zz'));
end $$;

-- What the report form suggests as it is typed: the usual FOH areas, and every place and piece of
-- equipment already used on a card. Free text — a suggestion is never required.
create or replace function fmaint_places(p_emp text) returns jsonb
language plpgsql stable security definer set search_path to 'public' as $$
declare s foh_staff;
begin
  s := fmaint_who(p_emp);
  return jsonb_build_object(
    'locations', (select coalesce(jsonb_agg(v order by v), '[]'::jsonb) from (
       select distinct v from (
         select unnest(array['Restaurant','Scala Lounge & Bar','Bar','Entrance & hostess desk','Guest toilets','Cashier','Service station','Staff area','Storage']) v
         union select location from fmaint_cards where not is_test) x where coalesce(v,'') <> '') y),
    'equipment', (select coalesce(jsonb_agg(v order by v), '[]'::jsonb) from (
       select distinct equipment v from fmaint_cards where not is_test and coalesce(equipment,'') <> '') y));
end $$;

-- ── mail queue ────────────────────────────────────────────────────────────
-- The bearer is the FOH anon key, already public in every FOH page. foh-maint-notify trusts no
-- caller: it only sends a row the database queued, to the recipients the database wrote.
create or replace function fmaint_kick(p_mail bigint) returns void
language plpgsql security definer set search_path to 'public' as $$
begin
  perform net.http_post(
    url := 'https://paoaivwtkzujmrgrfjuq.supabase.co/functions/v1/foh-maint-notify',
    headers := jsonb_build_object('Content-Type','application/json',
      'Authorization','Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhb2Fpdnd0a3p1am1yZ3JmanVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEwNzAxMzAsImV4cCI6MjA5NjY0NjEzMH0.VynG9PBeIaqRG2lkMEuzskkcB11EhR-UfO9eGYsaUxk'),
    body := jsonb_build_object('mail', p_mail));
end $$;
revoke all on function fmaint_kick(bigint) from public, anon, authenticated;

create or replace function fmaint_queue(p_card uuid, p_kind text) returns void
language plpgsql security definer set search_path to 'public' as $$
declare c fmaint_cards; v_to text[]; v_id bigint;
begin
  select * into c from fmaint_cards where id = p_card;
  if c.is_test then v_to := array['fguarracino@robertos.ae'];
  else
    if p_kind = 'new' then
      select array_agg(distinct lower(email)) into v_to from fmaint_people where active and role = 'technician';
    end if;
    -- 'check' always goes to the managers; 'new' does too while there is no technician
    if v_to is null or cardinality(v_to) = 0 then
      select array_agg(distinct lower(email)) into v_to from fmaint_people where active and role = 'manager';
    end if;
  end if;
  if v_to is null or cardinality(v_to) = 0 then return; end if;
  insert into fmaint_mail(card_id, kind, to_list, is_test) values (p_card, p_kind, v_to, c.is_test) returning id into v_id;
  perform fmaint_kick(v_id);
end $$;
revoke all on function fmaint_queue(uuid,text) from public, anon, authenticated;

-- ── cards ─────────────────────────────────────────────────────────────────
create or replace function fmaint_card_row(c fmaint_cards) returns jsonb
language sql stable as $$ select to_jsonb(c) - 'tech_signed_id' - 'checked_id' - 'reported_by_id' - 'tech_id' $$;

create or replace function fmaint_list(p_emp text) returns jsonb
language plpgsql stable security definer set search_path to 'public' as $$
declare s foh_staff;
begin
  s := fmaint_who(p_emp);
  return jsonb_build_object(
    'cards', coalesce((select jsonb_agg(jsonb_build_object('id', c.id, 'card_no', c.card_no, 'status', c.status,
        'location', c.location, 'equipment', c.equipment, 'problem', left(c.problem, 140), 'reported_by', c.reported_by, 'reported_at', c.reported_at,
        'tech_name', c.tech_name, 'hold_reason', c.hold_reason, 'completed_at', c.completed_at, 'checked_at', c.checked_at, 'checked_by', c.checked_by,
        'sent_back_at', c.sent_back_at, 'media', jsonb_array_length(c.media), 'is_test', c.is_test,
        'photos', (select count(*) from jsonb_array_elements(c.media) m where m->>'kind' = 'photo'),
        'videos', (select count(*) from jsonb_array_elements(c.media) m where m->>'kind' = 'video'))
      order by c.reported_at desc) from fmaint_cards c
      where (c.checked_at is null or c.checked_at > now() - interval '120 days')
        and (not c.is_test or s.name ~* '^zz')), '[]'::jsonb));
end $$;

create or replace function fmaint_get(p_emp text, p_id uuid) returns jsonb
language plpgsql stable security definer set search_path to 'public' as $$
declare s foh_staff; c fmaint_cards;
begin
  s := fmaint_who(p_emp);
  select * into c from fmaint_cards where id = p_id;
  if c.id is null then raise exception 'no_card' using errcode = 'P0001'; end if;
  return jsonb_build_object('card', fmaint_card_row(c),
    'me', jsonb_build_object('tech', fmaint_has(s.id,'technician'), 'manager', fmaint_has(s.id,'manager'),
                             'signed_as_tech', c.tech_signed_id is not distinct from s.id));
end $$;

-- Opening a card as the technician is the moment it was READ.
create or replace function fmaint_read(p_emp text, p_id uuid) returns jsonb
language plpgsql security definer set search_path to 'public' as $$
declare s foh_staff; c fmaint_cards;
begin
  s := fmaint_who(p_emp);
  if not fmaint_has(s.id,'technician') then return null; end if;
  update fmaint_cards set read_at = now(), read_by = s.name,
         tech_id = coalesce(tech_id, s.id), tech_name = coalesce(tech_name, s.name),
         status = case when status = 'new' then 'acknowledged' else status end, updated_at = now()
   where id = p_id and read_at is null returning * into c;
  return case when c.id is null then null else fmaint_card_row(c) end;
end $$;

create or replace function fmaint_report(p_emp text, p_location text, p_equipment text, p_problem text, p_media jsonb) returns jsonb
language plpgsql security definer set search_path to 'public' as $$
declare s foh_staff; c fmaint_cards; m jsonb; v_media jsonb := '[]'::jsonb;
begin
  s := fmaint_who(p_emp);
  if length(trim(coalesce(p_location,''))) < 2 then raise exception 'no_location' using errcode = 'P0001'; end if;
  if length(trim(coalesce(p_equipment,''))) < 2 then raise exception 'no_equipment' using errcode = 'P0001'; end if;
  if length(trim(coalesce(p_problem,''))) < 3 then raise exception 'no_problem' using errcode = 'P0001'; end if;
  if jsonb_typeof(coalesce(p_media,'[]'::jsonb)) <> 'array' or jsonb_array_length(coalesce(p_media,'[]'::jsonb)) > 8 then raise exception 'bad_media' using errcode = 'P0001'; end if;
  for m in select * from jsonb_array_elements(coalesce(p_media,'[]'::jsonb)) loop
    if coalesce(m->>'path','') !~ '^c/[0-9a-f-]{36}/[A-Za-z0-9._-]+$'
       or not exists(select 1 from storage.objects o where o.bucket_id = 'fmaint-media' and o.name = m->>'path') then
      raise exception 'bad_media' using errcode = 'P0001'; end if;
    v_media := v_media || jsonb_build_array(jsonb_build_object('path', m->>'path',
      'kind', case when m->>'kind' = 'video' then 'video' else 'photo' end, 'size', coalesce((m->>'size')::bigint, 0)));
  end loop;
  insert into fmaint_cards(is_test, reported_by_id, reported_by, location, equipment, problem, media)
  values (s.name ~* '^zz' or trim(p_equipment) ~* '^zz', s.id, s.name, left(trim(p_location),120), left(trim(p_equipment),120), left(trim(p_problem),2000), v_media)
  returning * into c;
  perform fmaint_queue(c.id, 'new');
  return jsonb_build_object('id', c.id, 'card_no', c.card_no, 'is_test', c.is_test);
end $$;

create or replace function fmaint_amount(p text) returns numeric
language plpgsql immutable as $$
begin
  if p is null or trim(p) = '' then return null; end if;
  if trim(p) !~ '^\d{1,7}(\.\d{1,2})?$' then raise exception 'bad_amount' using errcode = 'P0001'; end if;
  return trim(p)::numeric;
end $$;

create or replace function fmaint_step(p_emp text, p_id uuid, p_op text, p_args jsonb) returns jsonb
language plpgsql security definer set search_path to 'public' as $$
declare s foh_staff; c fmaint_cards; a jsonb := coalesce(p_args,'{}'::jsonb); v_tech boolean; v_mgr boolean;
begin
  s := fmaint_who(p_emp);
  v_tech := fmaint_has(s.id,'technician'); v_mgr := fmaint_has(s.id,'manager');
  select * into c from fmaint_cards where id = p_id for update;
  if c.id is null then raise exception 'no_card' using errcode = 'P0001'; end if;
  if c.checked_at is not null then raise exception 'closed' using errcode = 'P0001'; end if;

  if p_op in ('start','hold','resume','assess','complete') then
    if not v_tech then raise exception 'not_tech' using errcode = 'P0001'; end if;
    if c.status = 'completed' then raise exception 'completed' using errcode = 'P0001'; end if;
    update fmaint_cards set read_at = coalesce(read_at, now()), read_by = coalesce(read_by, s.name),
           tech_id = coalesce(tech_id, s.id), tech_name = coalesce(tech_name, s.name) where id = p_id;
  end if;

  if p_op = 'start' then
    update fmaint_cards set status = 'in_progress', started_at = coalesce(started_at, now()), hold_reason = null, updated_at = now() where id = p_id;
  elsif p_op = 'hold' then
    update fmaint_cards set status = 'on_hold', hold_at = now(), hold_reason = nullif(left(trim(coalesce(a->>'reason','')),200),''), updated_at = now() where id = p_id;
  elsif p_op = 'resume' then
    if c.status <> 'on_hold' then raise exception 'not_on_hold' using errcode = 'P0001'; end if;
    update fmaint_cards set status = 'in_progress', started_at = coalesce(started_at, now()), hold_reason = null, updated_at = now() where id = p_id;
  elsif p_op = 'assess' then
    update fmaint_cards set
      diagnosis = nullif(left(trim(coalesce(a->>'diagnosis','')),2000),''),
      cause     = nullif(left(trim(coalesce(a->>'cause','')),1000),''),
      solution  = nullif(left(trim(coalesce(a->>'solution','')),1000),''),
      est_cost  = fmaint_amount(a->>'est_cost'),
      est_time  = nullif(left(trim(coalesce(a->>'est_time','')),120),''),
      parts     = nullif(left(trim(coalesce(a->>'parts','')),1000),''),
      notes     = nullif(left(trim(coalesce(a->>'notes','')),2000),''),
      assessed_at = now(), assessed_by = s.name, updated_at = now()
    where id = p_id;
  elsif p_op = 'complete' then
    if trim(coalesce(a->>'code','')) <> trim(s.emp_id) then raise exception 'bad_code' using errcode = 'P0001'; end if;
    if length(trim(coalesce(a->>'work_done',''))) < 3 then raise exception 'no_work' using errcode = 'P0001'; end if;
    if fmaint_amount(a->>'final_cost') is null then raise exception 'no_cost' using errcode = 'P0001'; end if;
    update fmaint_cards set status = 'completed', work_done = left(trim(a->>'work_done'),2000), final_cost = fmaint_amount(a->>'final_cost'),
           completed_at = now(), tech_signed_id = s.id, tech_signed_by = s.name, hold_reason = null, updated_at = now()
     where id = p_id;
    perform fmaint_queue(p_id, 'check');
  elsif p_op = 'check' then
    if not v_mgr then raise exception 'not_manager' using errcode = 'P0001'; end if;
    if c.status <> 'completed' then raise exception 'not_completed' using errcode = 'P0001'; end if;
    if trim(coalesce(a->>'code','')) <> trim(s.emp_id) then raise exception 'bad_code' using errcode = 'P0001'; end if;
    if c.tech_signed_id = s.id then raise exception 'same_person' using errcode = 'P0001'; end if;
    update fmaint_cards set checked_at = now(), checked_id = s.id, checked_by = s.name, updated_at = now() where id = p_id;
  elsif p_op = 'send_back' then
    if not v_mgr then raise exception 'not_manager' using errcode = 'P0001'; end if;
    if c.status <> 'completed' then raise exception 'not_completed' using errcode = 'P0001'; end if;
    if length(trim(coalesce(a->>'note',''))) < 3 then raise exception 'no_note' using errcode = 'P0001'; end if;
    update fmaint_cards set status = 'in_progress', completed_at = null, tech_signed_id = null, tech_signed_by = null,
           sent_back_at = now(), sent_back_by = s.name, sent_back_note = left(trim(a->>'note'),500), updated_at = now() where id = p_id;
  else
    raise exception 'bad_op' using errcode = 'P0001';
  end if;
  select * into c from fmaint_cards where id = p_id;
  return fmaint_card_row(c);
end $$;

-- For the Home tile: no sign-in, counts only.
create or replace function fmaint_summary() returns jsonb
language sql stable security definer set search_path to 'public' as $$
  select jsonb_build_object(
    'open',    (select count(*) from fmaint_cards where checked_at is null and not is_test),
    'new',     (select count(*) from fmaint_cards where status = 'new' and not is_test),
    'to_check',(select count(*) from fmaint_cards where status = 'completed' and checked_at is null and not is_test))
$$;

grant execute on function fmaint_me(text), fmaint_places(text), fmaint_list(text), fmaint_get(text,uuid), fmaint_read(text,uuid),
  fmaint_report(text,text,text,text,jsonb), fmaint_step(text,uuid,text,jsonb), fmaint_summary() to anon, authenticated;

-- ── photos and videos ─────────────────────────────────────────────────────
-- Public bucket (a card's photos open by their long random address), 50 MB a file, images and
-- video only. anon may ADD a file and nothing else: no listing, no overwrite, no delete.
insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values ('fmaint-media', 'fmaint-media', true, 52428800, array['image/*','video/*'])
on conflict (id) do update set public = true, file_size_limit = 52428800, allowed_mime_types = array['image/*','video/*'];
drop policy if exists fmaint_media_add on storage.objects;
create policy fmaint_media_add on storage.objects for insert to anon, authenticated
  with check (bucket_id = 'fmaint-media' and name ~ '^c/[0-9a-f-]{36}/[A-Za-z0-9._-]+$');

-- ── people (7 Oct 2026, Francesco) ────────────────────────────────────────
-- The managers who sign off a FOH repair. Alessandro Longhi has NO employee ID in foh_staff yet
-- (one of the 7 codes chased with HR on 6 Oct), so he can report and receive the emails but
-- cannot sign until his code is added there. Oliver (technician) is added when he starts:
--   insert into fmaint_people(staff_id, role, email) select id, 'technician', '<his email>' from foh_staff where name = '<his name>';
insert into fmaint_people(staff_id, role, email)
select id, 'manager', e.email from foh_staff s
join (values ('Alessandro Longhi','alonghi@robertos.ae'), ('Jins Thomas','jthomas@robertos.ae'), ('Diego Tella','dtella@robertos.ae')) e(name, email)
  on e.name = s.name
where s.active
on conflict (staff_id, role) do update set email = excluded.email, active = true;

-- ── timer ─────────────────────────────────────────────────────────────────
-- Every 10 minutes: any mail still queued after 3 minutes, or failed fewer than 3 times, is retried.
create or replace function fmaint_retry() returns int
language plpgsql security definer set search_path to 'public' as $$
declare r record; n int := 0;
begin
  update fmaint_mail set status = 'failed', error = coalesce(error,'') || ' (stuck sending)' where status = 'sending' and created_at < now() - interval '30 minutes' and sent_at is null;
  for r in select id from fmaint_mail where (status = 'queued' and created_at < now() - interval '3 minutes') or (status = 'failed' and tries < 3) loop
    perform fmaint_kick(r.id); n := n + 1;
  end loop;
  return n;
end $$;
revoke all on function fmaint_retry() from public, anon, authenticated;

select cron.unschedule(jobid) from cron.job where jobname = 'fmaint-mail-retry';
select cron.schedule('fmaint-mail-retry', '*/10 * * * *', 'select fmaint_retry()');
